### ISSUE TITLE
Complex routing results in schema error when expression starts with '(' 

### ISSUE THREAD

**Issue by mikeh89** [Kong/atc-router#41]
Kong version: 3.1 

Issue: 
Currently attempting to migrate existing services from the 'v1' routing to the new Router Expressions Language and I'm running into schema errors when creating the new routing.  

Example: 
`curl --request PATCH \
--url https://kong-test.example.nl/services/service_id/routes/route_id \
--header 'Content-Type: multipart/form-data' \
--form 'expression=(http.host == "api-test.example.nl" || http.host == "api.example.nl") && (http.path ^= "/prefix/" || (http.path ^= "/prefix/" && (http.path =^ "/suffix1" || http.path =^ "/suffix2" || http.path =^ "/suffix3" || http.path =^ "/suffix3" || http.path =^ "/suffix4" || http.path =^ "/suffix5"))) && (http.method == "GET" || http.method == "POST" || http.method == "PATCH")'`

This returns the following error: 
`{"name":"schema violation","message":"schema violation (Router Expression failed validation:  --> 1:1\n  |\n1 | --------------------------5588f4caac5b101a--\n  | ^---\n  |\n  = expected term)","fields":{"@entity":["Router Expression failed validation:  --> 1:1\n  |\n1 | --------------------------5588f4caac5b101a--\n  | ^---\n  |\n  = expected term"]},"code":2}`

Running the request with a single host, without the '(' at the start of the expression, works as expected: 

`curl --request PATCH \
--url https://kong-test.example.nl/services/service_id/routes/route_id \
--header 'Content-Type: multipart/form-data' \
--form 'expression=http.host == "api-test.example.nl" && (http.path ^= "/prefix/" || (http.path ^= "/prefix/" && (http.path =^ "/suffix1" || http.path =^ "/suffix2" || http.path =^ "/suffix3" || http.path =^ "/suffix3" || http.path =^ "/suffix4" || http.path =^ "/suffix5"))) && (http.method == "GET" || http.method == "POST" || http.method == "PATCH")'`

Documentation suggests and includes an example showing that expressions starting with a '(' should work: https://docs.konghq.com/gateway/3.1.x/key-concepts/routes/expressions/ 

Multiple hosts have worked on other less complex routes. Also tested switching the order of the elements with no success. Can you confirm whether this is a bug, or whether this is an issue with the expression I'm using?

**Comment by pluveto** [comment]
Your expression is correct. But the expression string passed to the router parser is not your expression, it is a strange string that looks like `--------------------------5588f4caac5b101a--`.

**Comment by pluveto** [comment]
Can you provide your configuration details? Is `router_flavor` set to `expressions`?
Ref: https://docs.konghq.com/gateway/latest/reference/configuration/#router_flavor

**Comment by mikeh89** [comment]
Sure, I'm running Kong as a k8s deployment with the following env variables: 
```
- env:
  - name: KONG_ADMIN_LISTEN
    value: 0.0.0.0:8444
  - name: KONG_PROXY_LISTEN
    value: 0.0.0.0:8000
  - name: KONG_NGINX_DAEMON
    value: "off"
  - name: KONG_PROXY_ACCESS_LOG
    value: /dev/stdout
  - name: KONG_ADMIN_ACCESS_LOG
    value: /dev/stdout
  - name: KONG_PROXY_ERROR_LOG
    value: /dev/stderr
  - name: KONG_ADMIN_ERROR_LOG
    value: /dev/stderr
  - name: KONG_DATABASE
    value: postgres
  - name: KONG_PG_HOST
    valueFrom:
      configMapKeyRef:
        key: postgresqlhost
        name: kong
  - name: KONG_PG_PASSWORD
    valueFrom:
      secretKeyRef:
        key: databasepassword
        name: kong
  - name: KONG_PG_USER
    valueFrom:
      configMapKeyRef:
        key: databaseusername
        name: kong
  - name: KONG_PG_DATABASE
    value: kong
  - name: KONG_ROUTER_FLAVOR
    value: expressions
```
Other routes are working as expected
